---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python

  fixme:
    enabled: true

  radon:
    enabled: true
    config:
      python_version: 3

ratings:
  paths:
  - "podcast_archiver/**.py"
