ci:
    autoupdate_commit_msg: 'build(pre-commit): pre-commit.ci autoupdate'
    autoupdate_schedule: weekly
    autofix_commit_msg: 'ci(pre-commit): auto fixes from pre-commit hooks'
    autofix_prs: true
    skip:
      - mypy  # is local

default_install_hook_types:
  - pre-commit
default_stages:
  - pre-commit
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.5'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: check-ast

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      - id: poetry-check

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.6.1
    hooks:
      - id: cspell

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        require_serial: true
        pass_filenames: false
