name: Poetry Build

on:
  pull_request:

jobs:
  poetry-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - run: poetry build
