name: PyPI Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  poetry-publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3

      - uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
