name: Rich-codex

on:
  push:
    branches-ignore:
      - "main"

jobs:
  rich-codex:
    uses: janw/workflows/.github/workflows/poetry-rich-codex.yaml@main
    secrets:
      token: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
